### PR TITLE
DX-1846: Fix verify

### PR DESCRIPTION
**Pull request by asbjornu**
Fix the verify step by using a locally installed HTMLProofer gem instead of running it through Docker.

### CODE REVIEW

**Comment by asbjornu** [comment]
Verify now runs and should not fail with the terrible `137` error again. However, since it has not run for quite a while and perhaps because version 4 or HTMLProofer is more stringent in its proofing, there are now 137(!) internal link failures. 😄

One problem seems to be that `resource-sub-models.md` is a Checkout v3-only page, while there are technical reference pages linking to it from both Checkout v2 and Payment Menu. Since no `resource-sub-models.md` exists in Checkout v2 and Payment Menu, these links are thus broken:

```
* At /home/runner/work/developer.swedbankpay.com/developer.swedbankpay.com/_site/payment-menu/features/optional/unscheduled.html:8551:

  internally linking to /payment-menu/features/technical-reference/resource-sub-models#cancelled, which does not exist
```

Can you please figure out a solution to this, @arebra?

**Comment by asbjornu** [comment]
@arebra, a fine improvement!

> HTML-Proofer found 98 failures!

**Comment by asbjornu** [comment]
> HTML-Proofer found 77 failures!

🙌🏼

**Comment by asbjornu** [comment]
@arebra we are back!

> HTML-Proofer found 78 failures!

**Comment by asbjornu** [comment]
> HTML-Proofer found 29 failures!

\o/

**Review by arebra — APPROVED** [review]
Woop!

**Pull request merged**
