### PR TITLE
DX-2001: Removed recurrence token from table

### PR DESCRIPTION
**Pull request by arebra**

### CODE REVIEW

**Review by asbjornu — CHANGES_REQUESTED** [review]
I don't understand why `recurrenceToken` is removed. DX-2001 made me none the wiser. Care to elaborate in DX-2001 why this change is required?

**Comment by arebra** [comment]
In DX-1959 Simon wrote this:

The response shows, amongst other things, a recurrenceToken straight away on the Initial response, but you will need to send a GET towards the PaymentOrderID, after a purchase has been made, in order to receive this information.

As the initial create payment response does not return the recurrenceToken, I removed it from the table.

Did a sanity check with Sandra.

**Review by asbjornu — APPROVED** [review]
>The response shows, amongst other things, a recurrenceToken straight away on the Initial response, but you will need to send a GET towards the PaymentOrderID, after a purchase has been made, in order to receive this information.
>
>As the initial create payment response does not return the recurrenceToken, I removed it from the table.

So `recurrenceToken` is described in other examples?

**Comment by arebra** [comment]
I'm going to have to triple check this.

**Pull request merged**
