### PR TITLE
Fixed typo in introduction.md

### PR DESCRIPTION
**Pull request by asbjornu**
Rebase of PayEx/developer.swedbankpay.com#1.

### CODE REVIEW

**Review by arebra — APPROVED** [review]
A true poet!

**Comment by asbjornu** [comment]
@muzukashiine, can you please sign our [CLA](https://cla-assistant.io/SwedbankPay/developer.swedbankpay.com?pullRequest=1592)? 🙏🏼

**Comment by muzukashiine** [comment]
> @muzukashiine, can you please sign our [CLA](https://cla-assistant.io/SwedbankPay/developer.swedbankpay.com?pullRequest=1592)? 🙏🏼

Done.

**Comment by muzukashiine** [comment]
> A true poet!

Also the only person in the world having a pull request on that other repository! Do I get a medal? 🥇

**Comment by asbjornu** [comment]
@muzukashiine, of course!

Gold medal

**Pull request merged**
