### PR TITLE
Feature/dx 155 checkout/3 ds2

### PR DESCRIPTION
**Pull request by trieutran91**
3DS2 documentation is added to checkout as a subsection in this branch.

Notes:

1. Some tables are not adequate visually. The best example is the first two tables where the cell width differs. Tried some simple tricks to conform the tables, unfortunately without success. Maybe we can take a look at this?

2. In the description for the "payeeInfo.payeeReference" property, there is a link to the Technical Reference section at the old Developer Portal (https://developer.payex.com/xwiki/wiki/developer/view/Main/ecommerce/technical-reference/#HPayeeReference). Since we don't have the equivalent section at the new portal I haven't applied a link yet.

3. I noticed that Resource's menu is on the checkout pages. I believe this should be removed?

### CODE REVIEW

**Comment by trieutran91** [comment]
I see. My bad, I somehow got this completely wrong. I'll go through the existing material in the Checkout documentation

**Comment by asbjornu** [comment]
No worries, I take a large part of the blame for not being clearer in my initial description. Now get home and have a great weekend! :smile:

**Comment by asbjornu** [comment]
I also notice that the branch is started from your work in the resources branch and not from an up to date `HEAD` of the `master` branch. Let’s discuss that on Monday.

**Comment by trieutran91** [comment]
Yes I got to take look at that again. I have an idea about why it started from the resources branch.
In the meantime, enjoy the weekend! 😊

**Pull request closed without merging**
