### PR TITLE
DX-1733: Added TechRef icons in checkout v3

### PR DESCRIPTION
**Pull request by arebra**

### CODE REVIEW

**Review by trieutran91 — COMMENTED** [review]
The icons that are added, are not visible when I run this locally. From what I can see, you are doing everything correct. This might be related to https://payexjira.atlassian.net/jira/software/projects/DX/boards/179/backlog?selectedIssue=DX-1737.
Do you have any input on this @asbjornu ?

**Comment by asbjornu** [comment]
I think this looks right, @trieutran91?

image

I think too many cards are still using the `credit_card` icon, but otherwise I think it's OK?

**Comment by trieutran91** [comment]
It certainly does! This is how it looks at my end:

image

I agree. A bit too many `credit_card`. You could perhaps replace it with `http` for Resource Models

**Review by trieutran91 — APPROVED** [review]

**Comment by asbjornu** [comment]
Hm, weird that all icons are blank for you, @trieutran91. Can you try to do `git clean -xdf` before you do `bundle exec jekyll serve` or `docker compose up`?

**Comment by trieutran91** [comment]
> Hm, weird that all icons are blank for you, @trieutran91. Can you try to do `git clean -xdf` before you do `bundle exec jekyll serve` or `docker compose up`?

That worked like magic! 🪄

**Comment by arebra** [comment]
I can look for better options than the credit card, but now they aren't empty at least :) I'll create a task for it.

**Pull request merged**
