### PR TITLE
Added emoji support

### PR DESCRIPTION
**Pull request by NullableInt**

### CODE REVIEW

**Comment by NullableInt** [comment]
> Does this actually work with GitHub Pages?

https://github.com/jekyll/jemoji Should work

**Comment by asbjornu** [comment]
Perhaps this can be tested in the theme repository first, just to be sure it works with GitHub Pages?

**Comment by NullableInt** [comment]
We can certainly try!

**Comment by NullableInt** [comment]
I've tested this locally, and adding emojies work.

**Comment by NullableInt** [comment]
> Can you test whether this is needed at all in the Developer Portal, when it's already done in the Jekyll theme?

It didn't work when the `_config.yml` wasn't updated

**Pull request merged**
